---
# tasks file for squid

- name: Include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "vars/{{ ansible_distribution }}.yml"
      skip: true
  tags:
    - squid

- name: Include release specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "vars/{{ ansible_distribution_release }}.yml"
      skip: true
  tags:
    - squid

- include: Archlinux.yml
  when: ansible_distribution == "Archlinux"
  tags:
    - squid

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags:
    - squid

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - squid

- name: Create Squid configuration file
  become: yes
  template:
    src: squid.conf.j2
    dest: "{{ squid_config_dir }}/squid.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart squid
  tags:
    - squid

- name: Create Squid error page CSS file
  become: yes
  template:
    src: errorpage.css.j2
    dest: "{{ squid_config_dir }}/errorpage.css"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart squid
  tags:
    - squid

- name: Create Squid MSNT auth configuration file
  become: yes
  template:
    src: msntauth.conf.j2
    dest: "{{ squid_config_dir }}/msntauth.conf"
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_release == "trusty"
  notify:
    - restart squid
  tags:
    - squid

- name: Ensure Squid service is started and enabled on boot
  become: yes
  service:
    name: "{{ squid_service_name }}"
    state: started
    enabled: yes
  tags:
    - squid
